// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Post = sequelize.define(
    "Post",
    {
      id: {
        type: DataTypes.BIGINT,
        primaryKey: true,
        allowNull: false,
      },
      title: {
        type: DataTypes.STRING,
        allowNull: false,
      },
      post_id: {
        type: DataTypes.BIGINT,
      },
      createdAt: {
        type: DataTypes.DATE,
      },
      updatedAt: {
        type: DataTypes.DATE,
      },
    },
    {
      tableName: "posts",
    }
  );

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Post.associate = (models) => {
    Post.belongsTo(models.Post, {
      foreignKey: {
        name: "postIdKey",
        field: "post_id",
      },
      targetKey: "id",
      as: "Category",
    });
    Post.hasMany(models.Post, {
      foreignKey: {
        name: "postIdKey",
        field: "post_id",
      },
      sourceKey: "id",
      as: "subPosts",
    });
  };

  return Post;
};
